# Generated by Django 5.2.7 on 2025-10-08 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2eafad33-a569-48d0-aa71-7c3104860bf9'), primary_key=True, serialize=False),
        ),
    ]
