# Generated by Django 5.2.7 on 2025-10-15 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7693b173-53a6-4f05-8193-3e450e3dd008'), primary_key=True, serialize=False),
        ),
    ]
