# Generated by Django 5.2.7 on 2025-10-20 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fd0389e-2068-42be-b0ac-6e3fd5e8b5b7'), primary_key=True, serialize=False),
        ),
    ]
