# Generated by Django 5.2.7 on 2025-10-28 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_borrower_alter_bookinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ffd1b1b2-6fac-41e2-889b-885b7dc056f8'), primary_key=True, serialize=False),
        ),
    ]
